# 22 fragmentos de manuais médicos — base de conhecimento do assistente RAG
MEDICAL_DOCS = [
    "Cefaleia pulsátil (enxaqueca) é caracterizada por dor latejante unilateral, fotofobia, fonofobia e náusea. Pode durar de 4 a 72 horas sem tratamento.",
    "Fotofobia é a hipersensibilidade anormal à luz, comumente associada a enxaqueca, meningite e uveíte. O paciente refere desconforto intenso em ambientes iluminados.",
    "Fonofobia refere-se à hipersensibilidade ao som. Sintoma clássico da crise migranosa, frequentemente acompanhada de fotofobia e náusea.",
    "Náusea e vômito durante episódios de cefaleia indicam comprometimento do sistema nervoso autônomo, típico de enxaqueca com ou sem aura.",
    "Aura migranosa: sintomas neurológicos transitórios que precedem a cefaleia — escotomas cintilantes, parestesias unilaterais e disartria temporária.",
    "Meningite bacteriana apresenta tríade clássica: febre alta, rigidez de nuca (sinal de Kernig positivo) e cefaleia intensa. Emergência médica.",
    "Hipertensão intracraniana: cefaleia progressiva que piora ao decúbito, vômitos em jato e papiledema ao exame de fundo de olho.",
    "Cefaleia tensional: bilateral, em pressão ou aperto, intensidade leve a moderada, sem náusea significativa. Associada a estresse e tensão muscular cervical.",
    "Neuralgia do trigêmeo: dor facial unilateral súbita tipo choque elétrico, duração de segundos, desencadeada por toque, mastigação ou fala.",
    "Crise hipertensiva: PA sistólica > 180 mmHg precipita cefaleia severa, geralmente occipital matinal. Pode evoluir para encefalopatia hipertensiva.",
    "AVC isquêmico: cefaleia súbita intensa, hemiplegia, afasia e desvio conjugado do olhar. Janela terapêutica de 4,5 h para trombólise IV.",
    "Hemorragia subaracnóidea por aneurisma roto: cefaleia em trovoada (thunderclap headache) de início abrupto, com rigidez de nuca e fotofobia.",
    "Glaucoma agudo de ângulo fechado: dor ocular intensa com cefaleia ipsilateral, visão turva com halos coloridos e midríase fixa. Emergência oftalmológica.",
    "Sinusite aguda: pressão e cefaleia frontal ou maxilar que piora ao inclinar a cabeça, secreção nasal purulenta e febre baixa.",
    "Cefaleia em salvas (cluster headache): unilateral, orbitária, excruciante, duração de 15-180 min, com lacrimejamento e rinorreia ipsilateral.",
    "Hipoglicemia: glicemia < 70 mg/dL causa cefaleia, sudorese, tremores, confusão mental e visão turva. Tratamento: carboidratos de absorção rápida.",
    "Trombose venosa cerebral: cefaleia progressiva, convulsões focais e déficits neurológicos variáveis. Risco elevado no puerpério e uso de anticoncepcionais orais.",
    "Miastenia gravis: ptose palpebral, diplopia, disfagia e fraqueza muscular flutuante ao longo do dia. SFEMG é o exame de maior sensibilidade diagnóstica.",
    "Esclerose múltipla: neurite óptica (dor ao movimento ocular com perda visual), parestesias, ataxia e fenômeno de Lhermitte (choque ao flexionar a cervical).",
    "Hipertireoidismo: taquicardia, tremor fino, perda de peso, intolerância ao calor, exoftalmia, diarreia e hiperreflexia. TSH suprimido no diagnóstico.",
    "Hipotireoidismo: bradicardia, ganho de peso, intolerância ao frio, constipação, pele seca e mixedema. TSH elevado com T4 livre reduzido confirma.",
    "Diabetes mellitus tipo 2: hiperglicemia crônica com polidipsia, poliúria, polifagia e perda de peso involuntária. HbA1c >= 6,5% confirma o diagnóstico.",
]
